before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  binary: bd
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- tap:
    owner: sachaos
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/sachaos/bd
  description: Describe binary string
  skip_upload: auto
  test: |
    system "#{bin}/bd", "0x45"
